---
title: "20-bp MPRA Barcodes"
output:
  html_document:
    df_print: paged
---

3 modifications:
  1) Increasing barcode length from 10 bp to 20 bp
  2) Adding a filter step using transcription factor binding site library
      - Screen out candidates with binding sites
  3) Allowing regeneration of barcodes in each step to always end with 1000 barcodes

```{r}
setwd("/Users/yshibata/Documents/GitHub/20bpMPRAdesign")
library("tidyverse")
library("phylotools")

list.files()
link <- "AllmiRNAseeds.txt"
rawlines <- readLines(file(link))
lines <- paste(rawlines[c(TRUE, FALSE)], rawlines[c(FALSE, TRUE)], collapse = "\n")
dat <- read.table(text = lines, na.string = "*") %>%
unite(species, V3, V4)
HumanmiRNAseeds <- filter(dat, species == "Homo_sapiens") %>%
  subset(select = c(V1, V6))
colnames(HumanmiRNAseeds) <- c('seq.name', 'seq.text')
print(HumanmiRNAseeds)
dat2fasta(HumanmiRNAseeds, "HumanmiRNAseedsF.fasta")
```

`

```{r}
setwd("/Users/yshibata/Documents/GitHub/20bpMPRAdesign")
library("tidyverse")
library("phylotools")

list.files()
link <- "hg38_motif.csv"
dat <- read.csv(link, header = TRUE)
colnames(dat) <- c('seq.name', 'seq.text')
print(dat)
dat2fasta(dat, outfile = "TFBSChiPBase.fasta")
```

`

```{r}
setwd("/Users/yshibata/Documents/GitHub/20bpMPRAdesign")
library("Biostrings")
library("tidyverse")
library("universalmotif")
library("TFBSTools")

nucruns <- vector(mode = 'character', length = 4) %>% DNAStringSet
ni = 1
for (i in 4) {
  for (j in c('A', 'G', 'T', 'C')) {
    nucruns[ni] = rep(j, i) %>% paste(collapse = '') %>% DNAStringSet
    ni = ni + 1
  }
}

barcodes <- create_sequences("DNA", 500000, 20, rng.seed = 1) %>% DNAStringSet
##bp changed from 10 to 20
paste0('Sample of random sequences generated')
head(barcodes)
cat(paste0('done generating bacrcodes at ', Sys.time()))
print(length(barcodes))
summary(barcodes)

##missing nucleotides filter
missingone <- apply(alphabetFrequency(barcodes) [,1:4], 1, function(x){any(x == 0)})
barcodes <- barcodes[!missingone]
cat(paste0('done removing barcodes missing a nucleotide at ', Sys.time()))
print(length(barcodes))
summary(barcodes)

##4 bp repeats filter
hasnucruns <- vcountPDict(nucruns, barcodes) %>% colSums
hasnucruns <- hasnucruns > 0
barcodes <- barcodes[!hasnucruns]
cat(paste0('done removing barcodes with runs of 4 or more at ', Sys.time()))
print(length(barcodes))
summary(barcodes)

##TCT sequences filter
seqremove <- DNAStringSet("TCT")
TCTseq <- vcountPDict(seqremove, barcodes) %>% colSums
TCTseq <- TCTseq > 0
barcodes <- barcodes[!TCTseq]
cat(paste0('done removing sequences with TCT', Sys.time()))
print(length(barcodes))
summary(barcodes)

##seed miRNAs filter
allSeeds <- readRNAStringSet("HumanmiRNAseedsF.fasta")
allSeedsmRNA <- Biostrings::reverseComplement(allSeeds)
allSeedsDNA <- DNAStringSet(allSeedsmRNA) %>% unique
seedSeqs <- allSeedsDNA %>% subseq(2, 7) %>% unique

haveSeedlist <- vwhichPDict(seedSeqs, barcodes)
save(list = c('barcodes', 'haveSeedlist'), file = '~/haveHumanRNAiSeeds.RData')
haveSeed <- sapply(haveSeedlist, function(x){length(x) > 0})
barcodes <- barcodes[!haveSeed]
cat(paste0('done removing those with mirSeeds at ', Sys.time()))
print(length(barcodes))
summary(barcodes)

##TFBSs filter
allTFBS <- readDNAStringSet("TFBSChiPBase.fasta")
allTFBSDNA <- DNAStringSet(allTFBS)

haveTFBSlist <- vwhichPDict(allTFBSDNA, barcodes)
save(list = c('barcodes', 'haveTFBSlist'), file = '~/haveHumanTFBS.RData')
haveTFBS <- sapply(haveTFBSlist, function(x){length(x) > 0})
barcodes <- barcodes[!haveTFBS]
cat(paste0('done removing those with TFBS at ', Sys.time()))
print(length(barcodes))
summary(barcodes)
write.csv(barcodes,'/Users/yshibata/Documents/GitHub/20bpMPRAdesign/20bpbarcodes.csv')

```


